version: '3'  

services:  
  nginx:
    image: nginx:latest
    container_name: nz01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: dz01
    depends_on:
      - db
    volumes:
      - ./start.sh:/start.sh
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis
    command: '/start.sh'

  db:
    image: postgres:latest
    container_name: pz01

  redis:
    image: redis:latest
    container_name: rz01
    ports:
     - '6379:6379'
